//! The fidelity corpus: the constructs that break naive terminal plumbing,
//! each named so a failure anywhere in six plans says which construct it
//! was, and the seeded generator for floods. The hand-authored constructs
//! are pinned by `assets/fidelity-corpus.bin`, because the compression
//! dictionary is trained on these bytes and a silent change to a construct
//! would be a silent change to the wire; the generated text is never
//! committed. Every non-ASCII byte here is written as an escape.

use core::fmt::{self, Display, Formatter};

/// The string terminator that ends an OSC or APC sequence.
const STRING_TERMINATOR: &[u8] = b"\x1b\\";

/// The bell, the other terminator an OSC accepts.
const BELL: &[u8] = b"\x07";

/// The width of every length and count in the serialized corpus.
const WORD_WIDTH: usize = 4;

/// The six low bits of every byte lane of a xorshift word: what the
/// generator keeps of each byte, sixty-four values.
const LANE_MASK: u64 = 0x3f3f_3f3f_3f3f_3f3f;

/// A space in every byte lane, added to the six kept bits of each: the sum
/// of a lane is at most 0x5f, so no lane carries into the next, and every
/// generated byte lies in the printable run from the space to the underscore
/// — punctuation, digits and capitals.
const PRINTABLE_BASE: u64 = 0x2020_2020_2020_2020;

/// The bytes one xorshift word yields.
const GENERATOR_WORD_LENGTH: usize = 8;

/// How many characters a generated line holds before its line break: nine
/// whole words, so a line break never falls inside a word's eight bytes.
const LINE_LENGTH: usize = 72;

/// Mixed into every seed: two to the sixty-fourth over the golden ratio,
/// whose bits are spread, so a small seed does not start from a nearly
/// empty state whose first words come out mostly spaces; it is also the
/// state a zero state is replaced with, since xorshift never leaves zero.
const SEED_SALT: u64 = 0x9E37_79B9_7F4A_7C15;

/// The first shift of Marsaglia's xorshift64 triple, whose period is two to
/// the sixty-fourth less one.
const SHIFT_LEFT_FIRST: u32 = 13;

/// The second shift of the triple.
const SHIFT_RIGHT: u32 = 7;

/// The third shift of the triple.
const SHIFT_LEFT_SECOND: u32 = 17;

/// One construct: a name, and the chunks it arrives in — a boundary
/// between chunks is part of the data.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Construct {
    /// What the construct is, for a failure to name.
    pub name: String,
    /// The bytes, in the writes they arrive as.
    pub chunks: Vec<Vec<u8>>,
}

/// Why serialized bytes are not a corpus.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum CorpusError {
    /// The bytes end inside a length, a count or a field.
    Truncated {
        /// Where the cut thing began: the four-byte word's start when a
        /// length or count is cut, the body's start when a body is cut.
        offset: usize,
    },
    /// A name is not UTF-8.
    Utf8 {
        /// Where the name began.
        offset: usize,
    },
}

impl Display for CorpusError {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        match self {
            CorpusError::Truncated { offset } => {
                write!(
                    formatter,
                    "the corpus ends inside the field at byte {offset}"
                )
            }
            CorpusError::Utf8 { offset } => {
                write!(formatter, "the name at byte {offset} is not UTF-8")
            }
        }
    }
}

impl std::error::Error for CorpusError {}

/// An OSC sequence: the introducer, the payload, a terminator.
fn osc(payload: &[u8], terminator: &[u8]) -> Vec<u8> {
    [b"\x1b]", payload, terminator].concat()
}

/// A single-chunk construct.
fn one(name: &str, bytes: Vec<u8>) -> Construct {
    Construct {
        name: name.to_owned(),
        chunks: vec![bytes],
    }
}

/// A two-chunk construct, whose boundary is the point.
fn two(name: &str, first: Vec<u8>, second: Vec<u8>) -> Construct {
    Construct {
        name: name.to_owned(),
        chunks: vec![first, second],
    }
}

/// Every construct, in the corpus's order.
#[must_use]
pub fn constructs() -> Vec<Construct> {
    vec![
        one(
            "kitty graphics payload",
            [b"\x1b_Ga=T,f=24,s=1,v=1;AAAA", STRING_TERMINATOR].concat(),
        ),
        one(
            "hyperlink open and close",
            [
                osc(b"8;;https://example.com/", STRING_TERMINATOR),
                b"link".to_vec(),
                osc(b"8;;", STRING_TERMINATOR),
            ]
            .concat(),
        ),
        one("clipboard write", osc(b"52;c;aGVsbG8=", BELL)),
        one("mark prompt start", osc(b"133;A", BELL)),
        one("mark command start", osc(b"133;B", BELL)),
        one("mark command executed", osc(b"133;C", BELL)),
        one("mark command finished", osc(b"133;D;0", BELL)),
        one("working directory", osc(b"7;file://host/tmp/work", BELL)),
        one("title terminated by BEL", osc(b"0;a title by bell", BELL)),
        one(
            "title terminated by ST",
            osc(b"2;a title by string terminator", STRING_TERMINATOR),
        ),
        two(
            "CSI split across two writes",
            b"\x1b[38;5;".to_vec(),
            b"196mcoloured\x1b[0m".to_vec(),
        ),
        one("wide CJK glyph", "\u{6f22}\u{5b57}".as_bytes().to_vec()),
        two(
            "lone escape at a chunk boundary",
            b"text\x1b".to_vec(),
            b"[1mbold\x1b[0m".to_vec(),
        ),
        one(
            "synchronized output begin and end",
            b"\x1b[?2026ha whole frame\x1b[?2026l".to_vec(),
        ),
        one(
            "alternate screen round trip",
            b"main\x1b[?1049h\x1b[Halternate\x1b[?1049lmore main".to_vec(),
        ),
        one("keyboard protocol query", b"\x1b[?u".to_vec()),
        one("cursor position query", b"\x1b[6n".to_vec()),
    ]
}

/// Appends a length-prefixed field.
fn put(out: &mut Vec<u8>, bytes: &[u8]) {
    let length = u32::try_from(bytes.len()).unwrap_or(u32::MAX);
    out.extend_from_slice(&length.to_le_bytes());
    out.extend_from_slice(bytes);
}

/// The serialized form of constructs: for each, a length-prefixed name, a
/// chunk count, and length-prefixed chunks, every length four bytes
/// little-endian.
#[must_use]
pub fn serialize(constructs: &[Construct]) -> Vec<u8> {
    let mut out = Vec::new();
    for construct in constructs {
        put(&mut out, construct.name.as_bytes());
        let count = u32::try_from(construct.chunks.len()).unwrap_or(u32::MAX);
        out.extend_from_slice(&count.to_le_bytes());
        for chunk in &construct.chunks {
            put(&mut out, chunk);
        }
    }
    out
}

/// A cursor over serialized bytes.
struct Reader<'bytes> {
    /// The bytes.
    bytes: &'bytes [u8],
    /// How far they have been read.
    offset: usize,
}

impl<'bytes> Reader<'bytes> {
    /// The next four-byte little-endian word: a length or a count.
    ///
    /// # Errors
    ///
    /// [`CorpusError::Truncated`] when fewer than four bytes are left.
    fn word(&mut self) -> Result<usize, CorpusError> {
        let field = self.take(WORD_WIDTH)?;
        let word = <[u8; WORD_WIDTH]>::try_from(field)
            .map(u32::from_le_bytes)
            .unwrap_or_default();
        Ok(usize::try_from(word).unwrap_or(usize::MAX))
    }

    /// The next `count` bytes.
    ///
    /// # Errors
    ///
    /// [`CorpusError::Truncated`] when fewer are left.
    fn take(&mut self, count: usize) -> Result<&'bytes [u8], CorpusError> {
        let end = self.offset.saturating_add(count);
        let taken = self
            .bytes
            .get(self.offset..end)
            .ok_or(CorpusError::Truncated {
                offset: self.offset,
            })?;
        self.offset = end;
        Ok(taken)
    }

    /// The next length-prefixed field.
    ///
    /// # Errors
    ///
    /// [`CorpusError::Truncated`] when the length or the field is cut short.
    fn field(&mut self) -> Result<&'bytes [u8], CorpusError> {
        let length = self.word()?;
        self.take(length)
    }
}

/// The constructs serialized bytes hold, in order.
///
/// # Errors
///
/// [`CorpusError::Truncated`] when the bytes end inside a field,
/// [`CorpusError::Utf8`] when a name is not UTF-8.
pub fn parse(bytes: &[u8]) -> Result<Vec<Construct>, CorpusError> {
    let mut reader = Reader { bytes, offset: 0 };
    let mut constructs = Vec::new();
    while reader.offset < bytes.len() {
        let name_offset = reader.offset;
        let name = std::str::from_utf8(reader.field()?)
            .map_err(|_error| CorpusError::Utf8 {
                offset: name_offset,
            })?
            .to_owned();
        let count = reader.word()?;
        let mut chunks = Vec::new();
        for _chunk in 0..count {
            chunks.push(reader.field()?.to_vec());
        }
        constructs.push(Construct { name, chunks });
    }
    Ok(constructs)
}

/// Pseudo-random printable text with line breaks and no escape byte, from a
/// seeded xorshift generator: the same seed and length give the same bytes,
/// so a flood is a flood and never an accidental sequence. Each word of the
/// generator becomes eight bytes from the space to the underscore at once,
/// which is what keeps 64 MiB under a second without optimization. The seed
/// is mixed with a salt; the one seed equal to the salt would start
/// from zero, where xorshift stays, so it starts from the salt instead and
/// generates what a zero seed does.
#[must_use]
pub fn generated(seed: u64, length: usize) -> Vec<u8> {
    let mut state = seed ^ SEED_SALT;
    if state == 0 {
        state = SEED_SALT;
    }
    let mut out = Vec::with_capacity(length);
    while out.len() < length {
        let line = LINE_LENGTH.min(length.saturating_sub(out.len()));
        let mut written: usize = 0;
        while written < line {
            state ^= state << SHIFT_LEFT_FIRST;
            state ^= state >> SHIFT_RIGHT;
            state ^= state << SHIFT_LEFT_SECOND;
            let word = (state & LANE_MASK)
                .wrapping_add(PRINTABLE_BASE)
                .to_le_bytes();
            let take = line.saturating_sub(written).min(GENERATOR_WORD_LENGTH);
            out.extend_from_slice(word.get(..take).unwrap_or_default());
            written = written.saturating_add(take);
        }
        if out.len() < length {
            out.push(b'\n');
        }
    }
    out
}
