/* Generated by `cargo xtask header` from crates/iznik-ffi. Do not edit. */

#ifndef IZNIK_H
#define IZNIK_H



#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * The version of the boundary this header describes.
 *
 * It changes when anything an application built against the header relies
 * on changes — a signature, a structure, the meaning of a code or of an
 * obligation — and not when the library merely gets better. An application
 * compares it with what `iznik_abi_version` says the library it loaded
 * was built for, and refuses to run on a mismatch rather than calling into a
 * library that means something else by the same names.
 */
#define IZNIK_ABI_VERSION 1

/**
 * The code a call gives when nothing went wrong.
 */
#define IZNIK_OK 0

/**
 * Something the application passed in was not what it said it was: a null
 * where one is not allowed, or bytes that are not UTF-8.
 */
#define IZNIK_INVALID_ARGUMENT 1

/**
 * No host of that name is held.
 */
#define IZNIK_UNKNOWN_HOST 2

/**
 * The host, or the machine this runs on, refused what was asked.
 */
#define IZNIK_REFUSED 3

/**
 * Which layer of the stack a failure came from.
 *
 * The first question anybody asks about a system this tall.
 */
typedef enum {
  /**
   * The link to the host: `ssh`, a socket, a network.
   */
  IZNIK_LAYER_TRANSPORT = 0,
  /**
   * Getting a server onto the host, or starting it.
   */
  IZNIK_LAYER_BOOTSTRAP = 1,
  /**
   * What the host's own daemon said.
   */
  IZNIK_LAYER_SERVER = 2,
  /**
   * The wire between them.
   */
  IZNIK_LAYER_PROTOCOL = 3,
  /**
   * This engine, on this machine.
   */
  IZNIK_LAYER_CLIENT = 4,
} iznik_layer;

/**
 * What an event is about, and how to read its payload.
 */
typedef enum {
  /**
   * A host moved from one state to another. The payload is the state as
   * UTF-8, for a person to read; a `HostStatus` event follows with the same
   * move for a program.
   */
  IZNIK_EVENT_KIND_HOST_STATE = 0,
  /**
   * The host's whole model. The payload is a `HostModel` as
   * `iznik_protocol::model::decode_host_model` reads it.
   */
  IZNIK_EVENT_KIND_SNAPSHOT = 1,
  /**
   * One numbered change. The payload is a `Delta` as
   * `iznik_protocol::delta::decode_delta` reads it.
   */
  IZNIK_EVENT_KIND_DELTA = 2,
  /**
   * The answer to a command. The payload is a `CommandOutcome` as
   * `iznik_protocol::command::decode_command_outcome` reads it, and the
   * command's own number is in `command_id`.
   */
  IZNIK_EVENT_KIND_COMMAND_RESULT = 3,
  /**
   * A shell-integration event. The payload is a `ToClient` as
   * `iznik_protocol::message::decode_to_client` reads it, which is a
   * `Mark` carrying the pane, the sequence and what happened.
   */
  IZNIK_EVENT_KIND_MARK = 4,
  /**
   * Something worth telling a person, as UTF-8.
   *
   * When it is about a command — one the host never answered, or one whose
   * answer could not be read — that command's own number is in
   * `command_id`, so whoever is waiting on it is released rather than left
   * waiting on an answer that will not come in the shape they expected.
   */
  IZNIK_EVENT_KIND_NOTIFICATION = 5,
  /**
   * A pane's own bytes, straight from the host. The pane is in `pane` and
   * the byte the first of them is, is in `sequence`.
   */
  IZNIK_EVENT_KIND_PANE_BYTES = 6,
  /**
   * A pane's screen, as the bytes that reproduce it. The pane is in `pane`,
   * the byte it is exact at is in `sequence`, and the size to reset a
   * surface to before feeding them is in `columns` and `rows`.
   */
  IZNIK_EVENT_KIND_SCREEN = 7,
  /**
   * The host has stopped sending a pane's output. The pane is in `pane`,
   * and there is no payload: a pane that has gone is not a state anybody
   * reads, it is a pane nothing more will arrive for.
   */
  IZNIK_EVENT_KIND_PANE_DETACHED = 8,
  /**
   * The same move as the `HostState` just before it, for a program to act
   * on rather than a person to read. The payload points at one
   * `iznik_host_status`, and `payload_length` is its size.
   */
  IZNIK_EVENT_KIND_HOST_STATUS = 9,
} iznik_event_kind;

/**
 * Where a host is, as a program reads it.
 */
typedef enum {
  /**
   * Nothing is being done about it.
   */
  IZNIK_HOST_STATE_KIND_DISCONNECTED = 0,
  /**
   * It is being asked what it is.
   */
  IZNIK_HOST_STATE_KIND_PROBING = 1,
  /**
   * A server is being put on it.
   */
  IZNIK_HOST_STATE_KIND_BOOTSTRAPPING = 2,
  /**
   * Its server is being started and greeted.
   */
  IZNIK_HOST_STATE_KIND_CONNECTING = 3,
  /**
   * Its server is being replaced.
   */
  IZNIK_HOST_STATE_KIND_UPGRADING = 4,
  /**
   * It is connected.
   */
  IZNIK_HOST_STATE_KIND_CONNECTED = 5,
  /**
   * Its link went, and it will be tried again.
   */
  IZNIK_HOST_STATE_KIND_RECONNECTING = 6,
  /**
   * It could not be reached.
   */
  IZNIK_HOST_STATE_KIND_FAILED = 7,
  /**
   * It is no longer held at all.
   */
  IZNIK_HOST_STATE_KIND_REMOVED = 8,
} iznik_host_state_kind;

/**
 * What kind of failure a host is in, which says whether waiting helps.
 */
typedef enum {
  /**
   * It is not failing.
   */
  IZNIK_FAILURE_KIND_NONE = 0,
  /**
   * Something that may pass by itself; it is tried again.
   */
  IZNIK_FAILURE_KIND_TRANSIENT = 1,
  /**
   * The host refused the credentials offered. Not tried again until
   * somebody asks.
   */
  IZNIK_FAILURE_KIND_CREDENTIALS = 2,
  /**
   * The host's key is not one this machine accepts — unknown, or changed.
   * Not tried again until somebody asks.
   */
  IZNIK_FAILURE_KIND_HOST_KEY = 3,
  /**
   * The host is a machine this build carries no server for. Not tried
   * again until somebody asks.
   */
  IZNIK_FAILURE_KIND_UNSUPPORTED = 4,
} iznik_failure_kind;

/**
 * Why an upgrade is on offer.
 */
typedef enum {
  /**
   * None is.
   */
  IZNIK_UPGRADE_KIND_NONE = 0,
  /**
   * The host runs another version than this build carries.
   */
  IZNIK_UPGRADE_KIND_VERSION = 1,
  /**
   * The host runs this version, missing features this build has.
   */
  IZNIK_UPGRADE_KIND_CAPABILITIES = 2,
} iznik_upgrade_kind;

/**
 * The client the application holds a pointer to.
 *
 * Opaque across the boundary: everything about it is behind the functions
 * below, and its size is nobody else's business.
 */
typedef struct iznik_client iznik_client;

/**
 * What the application makes a client with.
 *
 * Every field may be null, and null means the default.
 */
typedef struct {
  /**
   * Where this machine's own runtime files go.
   */
  const char *runtime_directory;
  /**
   * Where the servers this build carries are.
   */
  const char *artifacts_directory;
  /**
   * The program `ssh` asks for a passphrase with.
   */
  const char *askpass_program;
  /**
   * Where to write a log.
   */
  const char *log_path;
} iznik_configuration;

/**
 * Why a call did not do what it was asked.
 *
 * The application allocates it and passes a pointer; iznik fills it in. The
 * message points at storage this library owns and keeps until the next call
 * on the same thread — an application that needs it longer copies it, which
 * is the same rule every other buffer here follows.
 */
typedef struct {
  /**
   * Zero when nothing went wrong, and one of the codes above otherwise.
   */
  int code;
  /**
   * Which layer it came from.
   */
  iznik_layer layer;
  /**
   * What went wrong, as UTF-8 the application may display verbatim.
   */
  const char *message;
} iznik_error;

/**
 * One thing that happened.
 *
 * Every pointer in it is valid for the duration of the callback and no
 * longer.
 */
typedef struct {
  /**
   * What it is about.
   */
  iznik_event_kind kind;
  /**
   * The host it is about, as the user's own alias, UTF-8.
   */
  const char *host;
  /**
   * The pane it is about, for the kinds that name one; zero otherwise.
   */
  uint64_t pane;
  /**
   * Where in a pane's stream it sits, for the kinds that say; zero
   * otherwise.
   */
  uint64_t sequence;
  /**
   * How wide a `Screen` is, in cells; zero otherwise.
   *
   * A screen is drawn at a size, and a surface reset to the wrong one puts
   * every byte after it in the wrong cell — so the size travels with the
   * bytes rather than being remembered from whenever the pane was last
   * sized.
   */
  uint16_t columns;
  /**
   * How tall it is, in cells; zero otherwise.
   */
  uint16_t rows;
  /**
   * Which generation of the host's model a `Snapshot` is, or a `Delta`
   * produces; zero otherwise.
   *
   * A change belongs to exactly one generation and the encoded change does
   * not carry the number, so an application keeping a model of its own is
   * given it here — it is what `iznik_protocol`'s `apply` wants beside the
   * bytes, and what says whether anything was missed.
   */
  uint64_t generation;
  /**
   * This client's number for a command, on `CommandResult` and on a
   * `Notification` that is about one; zero otherwise.
   */
  uint64_t command_id;
  /**
   * The bytes, whose meaning `kind` decides.
   */
  const uint8_t *payload;
  /**
   * How many of them there are.
   */
  size_t payload_length;
  /**
   * For `PaneBytes`, how many of the payload's leading bytes carry
   * terminal queries the host has already answered; zero otherwise.
   *
   * **Obligation:** feed them to your emulator like the rest, but do not
   * send the answers it produces from them — the program has had them
   * once, and a second answer arrives as input it never asked for.
   */
  size_t answered_length;
  /**
   * For `PaneBytes`, the stream the bytes arrived on, which their credit
   * is returned against with `iznik_pane_credit`; zero otherwise.
   */
  uint64_t stream;
} iznik_event;

/**
 * What iznik calls when something happens.
 *
 * It is called on one thread and only that thread, so an application that
 * keeps state in its handler needs no lock of its own for it. It may call
 * back into iznik: no call holds a lock of iznik's while it works, and none
 * is held while a callback runs.
 *
 * Replacing it, or taking it away with a null, returns at once and waits for
 * nothing: a handler may be waiting for the very thread that asked. A call
 * already running may still be finishing; `iznik_wait_for_callbacks` is what
 * says it has, and so when the context given with it may be freed.
 */
typedef void (*iznik_event_callback)(const iznik_event *event, void *context);

/**
 * What iznik calls a pane's own handler with.
 *
 * Every one of them arrives on the same thread every other event does, and
 * none is called while iznik holds a lock of its own.
 */
typedef struct {
  /**
   * A pane's bytes, where they are; how many of the leading ones carry
   * terminal queries the host has already answered; and the stream they
   * arrived on, which their credit is returned against.
   *
   * **Obligation:** the bytes are valid for this call only. Feed them to a
   * surface before returning; do not keep the pointer. Feed the first
   * `answered` of them too, but do not send the answers your emulator
   * produces from those: the program has had them once. Return their
   * credit with this `stream`.
   */
  void (*output)(void *context,
                 const uint8_t *bytes,
                 size_t length,
                 size_t answered,
                 uint64_t stream);
  /**
   * The pane's screen, as the bytes that reproduce it at `sequence`.
   *
   * **Obligation:** reset the surface to `columns` by `rows` and feed it
   * these bytes before any further output. What came before them is gone.
   */
  void (*screen)(void *context,
                 uint64_t sequence,
                 uint16_t columns,
                 uint16_t rows,
                 const uint8_t *bytes,
                 size_t length);
  /**
   * A shell-integration event, as an encoded `ToClient` at `sequence`.
   */
  void (*mark)(void *context, uint64_t sequence, const uint8_t *bytes, size_t length);
  /**
   * The host has stopped sending this pane's output.
   */
  void (*detached)(void *context);
} iznik_pane_callbacks;

/**
 * A host's state, as a `HostStatus` event carries it.
 *
 * Every pointer in it is valid for the duration of the callback and no
 * longer.
 */
typedef struct {
  /**
   * Where the host is.
   */
  iznik_host_state_kind state;
  /**
   * What kind of failure it is in; `None` unless it is failing.
   */
  iznik_failure_kind failure;
  /**
   * Which layer the failure is in; meaningful only when `failure` is not
   * `None`.
   */
  iznik_layer layer;
  /**
   * Whether it will be tried again by itself.
   */
  bool retrying;
  /**
   * How many times it has failed since it was last connected, when it is
   * reconnecting; zero otherwise.
   */
  uint32_t attempt;
  /**
   * Why an upgrade is on offer, for a connected host; `None` otherwise.
   */
  iznik_upgrade_kind upgrade;
  /**
   * The version the host runs, as UTF-8, when an upgrade is on offer; null
   * otherwise.
   */
  const char *installed_version;
  /**
   * The version this build would put there, as UTF-8, when an upgrade is on
   * offer; null otherwise.
   */
  const char *bundled_version;
} iznik_host_status;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Makes a client.
 *
 * Answers null when it cannot, having filled in `error`.
 *
 * **Obligation:** the pointer this gives back is freed exactly once, with
 * `iznik_client_free`, and not used afterwards. Everything the
 * configuration points at may be freed as soon as this returns.
 *
 * Safety:
 *
 * `configuration` is null or points at a `iznik_configuration` whose strings are
 * null or null-terminated, and `error` is null or points at an `iznik_error` the
 * caller owns.
 */
iznik_client *iznik_client_new(const iznik_configuration *configuration, iznik_error *error);

/**
 * Ends a client: every host let go, every task stopped, the callback thread
 * ended.
 *
 * No callback begins once this has, and a call that arrives while it runs is
 * refused. Calls already under way — on any thread, a handler's among them —
 * are waited for, and so is a handler that is running, unless this is called
 * from inside a handler: then it returns without waiting for the handler it
 * is inside, no other callback is made, and the callback thread ends by
 * itself once that handler returns.
 *
 * **Obligation:** the pointer came from `iznik_client_new`, has not been
 * freed, and is not used afterwards — by the handler that called this, when a
 * handler did, as much as by anything else. A null pointer is nothing to free
 * and is ignored. Not called while holding a lock that a handler takes: it
 * waits for the handler that is running.
 *
 * Safety:
 *
 * As the obligation above.
 */
void iznik_client_free(iznik_client *client);

/**
 * Says what to call when something happens, and what to pass it.
 *
 * Every call arrives on one thread, and iznik holds no lock of its own while
 * one runs — a handler may call straight back in.
 *
 * Replacing it, or setting it to null, returns at once: no callback begins
 * with the old one afterwards, and one already running may still be
 * finishing — `iznik_wait_for_callbacks` waits for it.
 *
 * **Obligation:** whatever `context` points at outlives every callback made
 * with it: until the client is freed, or until the callback has been
 * replaced or set to null and `iznik_wait_for_callbacks` has returned. And it
 * may be used from the thread the callbacks arrive on, which is iznik's own
 * and not the one that called this.
 *
 * Safety:
 *
 * `client` is a live client from `iznik_client_new`.
 */
void iznik_set_event_callback(iznik_client *client, iznik_event_callback callback, void *context);

/**
 * The version of the boundary the library was built for, which an
 * application compares with the `IZNIK_ABI_VERSION` of the header it was
 * built against.
 */
uint32_t iznik_abi_version(void);

/**
 * This library's own version, for a log or an about box.
 *
 * The string is iznik's, null-terminated, and valid for as long as the
 * library is loaded; it is never freed.
 */
const char *iznik_version(void);

/**
 * Waits until every callback that had begun when this was called has
 * returned.
 *
 * Letting a pane go, attaching over it and replacing the event callback all
 * return at once: none of them waits for a handler, because a handler may be
 * waiting for the very thread that called them. What each promises is that
 * no callback *begins* with what was taken away once it has returned. This is
 * how an application learns that the ones already running have finished, and
 * so that what it gave them may be freed. Called from the callback thread, it
 * returns at once: the handler running there is the caller.
 *
 * **Obligation:** not called while holding a lock that a handler takes: it
 * waits for the handler that is running, which would be waiting for that
 * lock.
 *
 * Safety:
 *
 * `client` is a live client from `iznik_client_new`.
 */
void iznik_wait_for_callbacks(iznik_client *client);

/**
 * Begins holding a host, and connecting to it.
 *
 * Returns at once; what happens next arrives on the callback. An empty
 * alias, or one beginning with `-`, is refused with
 * `IZNIK_INVALID_ARGUMENT`: `ssh` would read it as an option.
 *
 * **Obligation:** `alias` is a null-terminated UTF-8 string, and may be freed
 * as soon as this returns.
 *
 * Safety:
 *
 * `client` is a live client, `alias` a null-terminated string, and `error`
 * null or an `iznik_error` the caller owns.
 */
int iznik_host_add(iznik_client *client, const char *alias, iznik_error *error);

/**
 * Stops holding a host.
 *
 * Safety:
 *
 * As `iznik_host_add`.
 */
int iznik_host_remove(iznik_client *client, const char *alias, iznik_error *error);

/**
 * Drops a host's link and opens another at once.
 *
 * Safety:
 *
 * As `iznik_host_add`.
 */
int iznik_host_reconnect(iznik_client *client, const char *alias, iznik_error *error);

/**
 * Replaces the server on a host with the one this build carries.
 *
 * Refuses while the host holds panes unless `force` says otherwise, because
 * replacing the daemon ends them.
 *
 * Safety:
 *
 * As `iznik_host_add`.
 */
int iznik_host_upgrade(iznik_client *client, const char *alias, bool force, iznik_error *error);

/**
 * Takes iznik off a host, and stops holding it.
 *
 * Safety:
 *
 * As `iznik_host_add`.
 */
int iznik_host_uninstall(iznik_client *client, const char *alias, iznik_error *error);

/**
 * Sends a session command, encoded as the protocol encodes it, and gives back
 * the number its answer will carry.
 *
 * The answer arrives as a `CommandResult` event carrying that number, and
 * what the command did arrives as a `Delta`. The events carry what the host
 * has said and only that — never a change this client is showing ahead of
 * it — so an application that wants a rename on the screen before the host
 * has agreed to it makes that change itself, and puts it back when the
 * `CommandResult` for its number says the host refused.
 *
 * **Obligation:** the bytes are the application's and may be freed as soon as
 * this returns; iznik reads them before it does.
 *
 * Safety:
 *
 * `client` is a live client, `host` a null-terminated string, `command`
 * points at `length` readable bytes, and `out_command_id` and `error` are
 * null or point at storage the caller owns.
 */
int iznik_command(iznik_client *client,
                  const char *host,
                  const uint8_t *command,
                  size_t length,
                  uint64_t *out_command_id,
                  iznik_error *error);

/**
 * Begins delivery of a pane's output to these handlers.
 *
 * **Obligation:** whatever `context` points at outlives every callback made
 * with it: until the client is freed, or until the pane has been detached or
 * attached again and `iznik_wait_for_callbacks` has returned. Detaching and
 * attaching again return at once — no callback begins with this context
 * afterwards — and a handler already running may still be reading it. And it
 * may be used from the thread the callbacks arrive on, which is iznik's own
 * and not the one that called this.
 *
 * Safety:
 *
 * `client` is a live client, `host` a null-terminated string, and `error`
 * null or an `iznik_error` the caller owns.
 */
int iznik_pane_attach(iznik_client *client,
                      const char *host,
                      uint64_t pane,
                      iznik_pane_callbacks callbacks,
                      void *context,
                      iznik_error *error);

/**
 * Ends it.
 *
 * Returns at once, waiting for no handler: no callback for this attachment
 * begins afterwards, and one already running may still be finishing, which
 * `iznik_wait_for_callbacks` waits for.
 *
 * Safety:
 *
 * As `iznik_pane_attach`.
 */
int iznik_pane_detach(iznik_client *client, const char *host, uint64_t pane, iznik_error *error);

/**
 * Returns credit for what a surface has consumed of the bytes a `stream`
 * delivered.
 *
 * The host sends no more than it has been given, so an application that never
 * calls this stalls its own pane and nothing else.
 *
 * **Obligation:** `stream` is the one the bytes arrived with — the `output`
 * callback's, or an event's `stream` — so that credit for bytes of a stream
 * the host has since replaced is ignored rather than given to the new one,
 * which never sent them. Zero means whichever stream is current.
 *
 * Safety:
 *
 * As `iznik_pane_attach`.
 */
int iznik_pane_credit(iznik_client *client,
                      const char *host,
                      uint64_t pane,
                      uint64_t stream,
                      uint32_t bytes,
                      iznik_error *error);

/**
 * Sends keystrokes, a paste, or an emulator's own answer to a program's
 * query.
 *
 * One call is one message on the wire, so a bracketed paste arrives as a
 * paste rather than as the keys it happens to contain — up to the most one
 * message carries, 1 048 563 bytes. A longer call is carried as several
 * messages to the pane, back to back and in order, with no other input to
 * that pane between them.
 *
 * **Obligation:** the bytes are read before this returns and may be freed as
 * soon as it does.
 *
 * Safety:
 *
 * As `iznik_pane_attach`, and `bytes` points at `length` readable bytes.
 */
int iznik_pane_input(iznik_client *client,
                     const char *host,
                     uint64_t pane,
                     const uint8_t *bytes,
                     size_t length,
                     iznik_error *error);

/**
 * Tells a pane it is another size.
 *
 * The application decides the size; every client sees the result as a
 * `PaneResized` change.
 *
 * Safety:
 *
 * As `iznik_pane_attach`.
 */
int iznik_pane_resize(iznik_client *client,
                      const char *host,
                      uint64_t pane,
                      uint16_t columns,
                      uint16_t rows,
                      iznik_error *error);

/**
 * Names the pane the person is looking at.
 *
 * Safety:
 *
 * As `iznik_pane_attach`.
 */
int iznik_pane_focus(iznik_client *client, const char *host, uint64_t pane, iznik_error *error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* IZNIK_H */
